import { Language } from './types';

export const LANGUAGES: Language[] = [
  {
    id: 'typescript',
    name: 'TypeScript',
    year: 2012,
    creator: 'Microsoft',
    category: ['Web', 'Mobile'],
    description: 'A strongly typed superset of JavaScript that compiles to plain JavaScript. It adds optional static typing to the language.',
    strength: ['Type Safety', 'Great Tooling', 'Vast Ecosystem'],
    weakness: ['Compilation Step', 'Complexity in Types'],
    helloWorld: 'console.log("Hello, World!");',
    paradigms: ['Multi-paradigm', 'Object-oriented', 'Functional'],
    rating: {
      learningCurve: 2,
      performance: 3,
      ecosystem: 5,
    },
  },
  {
    id: 'rust',
    name: 'Rust',
    year: 2010,
    creator: 'Graydon Hoare (Mozilla)',
    category: ['Systems', 'Web', 'AI'],
    description: 'A multi-paradigm system programming language focused on safety, especially safe concurrency. Rust is syntactically similar to C++.',
    strength: ['Memory Safety', 'High Performance', 'Fearless Concurrency'],
    weakness: ['Steep Learning Curve', 'Long Compile Times'],
    helloWorld: 'fn main() {\n    println!("Hello, World!");\n}',
    paradigms: ['Multi-paradigm', 'Compiled', 'Imperative'],
    rating: {
      learningCurve: 5,
      performance: 5,
      ecosystem: 3,
    },
  },
  {
    id: 'python',
    name: 'Python',
    year: 1991,
    creator: 'Guido van Rossum',
    category: ['Web', 'AI', 'Data Science'],
    description: 'An interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991.',
    strength: ['Readability', 'Huge Libraries', 'Fast Prototyping'],
    weakness: ['Execution speed', 'Dynamic Typing'],
    helloWorld: 'print("Hello, World!")',
    paradigms: ['Object-oriented', 'Imperative', 'Functional'],
    rating: {
      learningCurve: 1,
      performance: 2,
      ecosystem: 5,
    },
  },
  {
    id: 'go',
    name: 'Go',
    year: 2009,
    creator: 'Google',
    category: ['Systems', 'Web'],
    description: 'A statically typed, compiled programming language designed at Google. Go is syntactically similar to C, but with memory safety, garbage collection, and structural typing.',
    strength: ['Concurrency (Goroutines)', 'Simple Syntax', 'Fast Compilation'],
    weakness: ['Lack of Generics (pre-1.18)', 'Verbose Error Handling'],
    helloWorld: 'package main\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, World!")\n}',
    paradigms: ['Concurrent', 'Compiled', 'Imperative'],
    rating: {
      learningCurve: 2,
      performance: 4,
      ecosystem: 4,
    },
  },
  {
    id: 'swift',
    name: 'Swift',
    year: 2014,
    creator: 'Apple',
    category: ['Mobile', 'Systems'],
    description: 'A general-purpose, multi-paradigm, compiled programming language developed by Apple Inc. for iOS, iPadOS, macOS, watchOS, tvOS, and Linux.',
    strength: ['Modern Syntax', 'Performance', 'Safety Features'],
    weakness: ['Apple Ecosystem Focus', 'Frequent Changes'],
    helloWorld: 'print("Hello, World!")',
    paradigms: ['Protocol-oriented', 'Object-oriented', 'Functional'],
    rating: {
      learningCurve: 2,
      performance: 4,
      ecosystem: 4,
    },
  },
  {
    id: 'zig',
    name: 'Zig',
    year: 2016,
    creator: 'Andrew Kelley',
    category: ['Systems', 'Game Dev'],
    description: 'An imperative, general-purpose, statically typed, compiled system programming language designed for robustness, optimality, and maintainability.',
    strength: ['No Hidden Control Flow', 'C Interop', 'Low-level Control'],
    weakness: ['New/Immature Ecosystem', 'Niche Usage'],
    helloWorld: 'const std = @import("std");\n\npub func main() !void {\n    std.debug.print("Hello, World!\\n", .{});\n}',
    paradigms: ['Imperative', 'Manual Memory', 'Compiled'],
    rating: {
      learningCurve: 4,
      performance: 5,
      ecosystem: 1,
    },
  },
];
